version: '3'

services:
  wcagcompliancechecker:
    build:
      context: .
      dockerfile: Dockerfile
    image: wcagcompliancechecker
    container_name: wcagcompliancechecker
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:stable-perl
    container_name: webserver
    restart: unless-stopped
    ports:
      - "7006:7006"
    volumes:
      - web-root:/var/www/html
      - ./:/etc/nginx/conf.d
    depends_on:
      - wcagcompliancechecker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /
      o: bind